# Generated by Django 3.2.13 on 2022-10-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=7, max_length=200),
            preserve_default=False,
        ),
    ]
