# Generated by Django 3.2.13 on 2022-09-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField(default='null')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(default='null')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
