# Generated by Django 3.2.13 on 2022-10-18 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('imgboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgboard.imgboard')),
            ],
        ),
    ]
